/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rex1054
 */
public class lahan extends javax.swing.JPanel {

    Random random = new Random();
    boolean statusLahan = false;
    int jenisPohon;
    int statusAir;
    int umurPohon;
    int maxUmur;
    int hari;
    int tanamke = 0;

    /**
     * Creates new form lahan
     */
    public lahan() {
        initComponents();
        hari = 1;
        day.setText(String.valueOf(hari));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihan = new javax.swing.JButton();
        f16 = new javax.swing.JLabel();
        f15 = new javax.swing.JLabel();
        f14 = new javax.swing.JLabel();
        f13 = new javax.swing.JLabel();
        f12 = new javax.swing.JLabel();
        f11 = new javax.swing.JLabel();
        f10 = new javax.swing.JLabel();
        f09 = new javax.swing.JLabel();
        f08 = new javax.swing.JLabel();
        f07 = new javax.swing.JLabel();
        f06 = new javax.swing.JLabel();
        f05 = new javax.swing.JLabel();
        f04 = new javax.swing.JLabel();
        f03 = new javax.swing.JLabel();
        f02 = new javax.swing.JLabel();
        f01 = new javax.swing.JLabel();
        s16 = new javax.swing.JLabel();
        s15 = new javax.swing.JLabel();
        s14 = new javax.swing.JLabel();
        s13 = new javax.swing.JLabel();
        s12 = new javax.swing.JLabel();
        s11 = new javax.swing.JLabel();
        s10 = new javax.swing.JLabel();
        s9 = new javax.swing.JLabel();
        s8 = new javax.swing.JLabel();
        s7 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        t16 = new javax.swing.JLabel();
        t15 = new javax.swing.JLabel();
        t14 = new javax.swing.JLabel();
        t13 = new javax.swing.JLabel();
        t12 = new javax.swing.JLabel();
        t11 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        nextDay = new javax.swing.JButton();
        umur = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        jenis = new javax.swing.JLabel();
        air = new javax.swing.JLabel();
        tanamanke = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        field = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(845, 661));
        setMinimumSize(new java.awt.Dimension(845, 661));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pilihan.setBorderPainted(false);
        pilihan.setContentAreaFilled(false);
        pilihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanActionPerformed(evt);
            }
        });
        add(pilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 600, 280));
        add(f16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));
        add(f15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));
        add(f14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));
        add(f13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));
        add(f12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));
        add(f11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));
        add(f10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));
        add(f09, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));
        add(f08, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));
        add(f07, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));
        add(f06, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));
        add(f05, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        add(f04, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));
        add(f03, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));
        add(f02, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        f01.setToolTipText("");
        add(f01, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        add(s16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));
        add(s15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));
        add(s14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));
        add(s13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));
        add(s12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));
        add(s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));
        add(s10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));
        add(s9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));
        add(s8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));
        add(s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));
        add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));
        add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));
        add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));
        add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));
        add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));
        add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
        add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));
        add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));
        add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));
        add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));
        add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));
        add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));
        add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));
        add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));
        add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));
        add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));
        add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));
        add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));
        add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));
        add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));
        add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        nextDay.setText("Ganti Hari");
        nextDay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextDayActionPerformed(evt);
            }
        });
        add(nextDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, -1, -1));

        umur.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        umur.setForeground(new java.awt.Color(0, 0, 0));
        umur.setText("umur");
        add(umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Hari ke");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jenis Pohon");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Status Air");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Umur");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        day.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        day.setForeground(new java.awt.Color(0, 0, 0));
        day.setText("hari");
        add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jenis.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        jenis.setForeground(new java.awt.Color(0, 0, 0));
        jenis.setText("jenis");
        add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        air.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        air.setForeground(new java.awt.Color(0, 0, 0));
        air.setText("air");
        add(air, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        tanamanke.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        tanamanke.setForeground(new java.awt.Color(0, 0, 0));
        tanamanke.setText("0");
        add(tanamanke, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Game Sans Serif 7", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tanam ke");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/lahan1.png"))); // NOI18N
        add(field, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanActionPerformed
        // Lahan Klik
        JOptionPane pane = new JOptionPane("");
        Object[] options = new String[]{"Tanam", "Siram", "Panen", "Bersihkan", "Batal"};
        pane.setOptions(options);
        JDialog dialog = pane.createDialog(new JFrame(), "Pilihan");
        dialog.show();
        Object obj = pane.getValue();
        if (obj.equals("Tanam")) {
            if (statusLahan == true) {
                JOptionPane.showMessageDialog(null, "Lahan sudah ditanami!");
                JOptionPane.showMessageDialog(null, "Gagal menanam!");
            } else {
                JOptionPane pane2 = new JOptionPane("");
                Object[] options2 = new String[]{"Pohon1", "Pohon2", "Pohon3", "Pohon4", "Batal"};
                pane2.setOptions(options2);
                JDialog dialog2 = pane2.createDialog(new JFrame(), "Pohon");
                dialog2.show();
                Object obj2 = pane2.getValue();
                if (obj2.equals("Pohon1")) {
                    tanamke += 1;
                    statusLahan = true;
                    jenisPohon = 1;
                    statusAir = 50;
                    umurPohon = 1;
                    maxUmur = 7;
                    tanamanke.setText(String.valueOf(tanamke));
                    jenis.setText("Pohon 1");
                    air.setText(String.valueOf(statusAir));
                    umur.setText(String.valueOf(umurPohon));
                    f01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    f16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon1.png")));
                    JOptionPane.showMessageDialog(null, "Berhasil menanam!");
                } else if (obj2.equals("Pohon2")) {
                    tanamke += 1;
                    statusLahan = true;
                    jenisPohon = 2;
                    statusAir = 50;
                    umurPohon = 1;
                    maxUmur = 10;
                    jenis.setText("Pohon 2");
                    tanamanke.setText(String.valueOf(tanamke));
                    air.setText(String.valueOf(statusAir));
                    umur.setText(String.valueOf(umurPohon));
                    f01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    f16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon2.png")));
                    JOptionPane.showMessageDialog(null, "Berhasil menanam!");
                } else if (obj2.equals("Pohon3")) {
                    tanamke += 1;
                    statusLahan = true;
                    jenisPohon = 3;
                    statusAir = 50;
                    umurPohon = 1;
                    maxUmur = 15;
                    jenis.setText("Pohon 3");
                    tanamanke.setText(String.valueOf(tanamke));
                    air.setText(String.valueOf(statusAir));
                    umur.setText(String.valueOf(umurPohon));
                    f01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    f16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon3.png")));
                    JOptionPane.showMessageDialog(null, "Berhasil menanam!");
                } else if (obj2.equals("Pohon4")) {
                    tanamke += 1;
                    statusLahan = true;
                    jenisPohon = 4;
                    statusAir = 50;
                    umurPohon = 1;
                    maxUmur = 25;
                    jenis.setText("Pohon 4");
                    tanamanke.setText(String.valueOf(tanamke));
                    air.setText(String.valueOf(statusAir));
                    umur.setText(String.valueOf(umurPohon));
                    f01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    f16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/pohon4.png")));
                    JOptionPane.showMessageDialog(null, "Berhasil menanam!");
                }
            }
        } else if (obj.equals("Siram")) {
            if (statusLahan == false) {
                JOptionPane.showMessageDialog(null, "Silahkan melakukan penanaman terlebih dahulu");
            } else if (statusAir == 100) {
                JOptionPane.showMessageDialog(null, "Pohon masih segar, siram lagi di lain hari!");
            } else {
                statusAir += 25;
                if (statusAir >= 100) {
                    statusAir = 100;
                }
                JOptionPane.showMessageDialog(null, "Penyiraman berhasil!");
                air.setText(String.valueOf(statusAir));
            }
        } else if (obj.equals("Panen")) {
            if (statusLahan == false) {
                JOptionPane.showMessageDialog(null, "Silahkan menanam terlebih dahulu!");
            } else
            if (umurPohon >= maxUmur) {
                f01.setIcon(null);
                f02.setIcon(null);
                f03.setIcon(null);
                f04.setIcon(null);
                f05.setIcon(null);
                f06.setIcon(null);
                f07.setIcon(null);
                f08.setIcon(null);
                f09.setIcon(null);
                f10.setIcon(null);
                f11.setIcon(null);
                f12.setIcon(null);
                f13.setIcon(null);
                f14.setIcon(null);
                f15.setIcon(null);
                f16.setIcon(null);
                JOptionPane.showMessageDialog(null, "Berhasil Panen! \n"
                        + "Hasil panen dimasukkan ke dalam inventori");
                jenisPohon = 0;
                jenis.setText("tidak ada");
                air.setText("0");
                umur.setText("0");
                t1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
                t16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/IMG/trunk2.png")));
            }
        } else if (obj.equals("Bersihkan")) {
            t1.setIcon(null);
            t2.setIcon(null);
            t3.setIcon(null);
            t4.setIcon(null);
            t5.setIcon(null);
            t6.setIcon(null);
            t7.setIcon(null);
            t8.setIcon(null);
            t9.setIcon(null);
            t10.setIcon(null);
            t11.setIcon(null);
            t12.setIcon(null);
            t13.setIcon(null);
            t14.setIcon(null);
            t15.setIcon(null);
            t16.setIcon(null);
            JOptionPane.showMessageDialog(null, "Lahan telah dibersihkan! \n"
                    + "siap untuk ditanam kembali");
            statusLahan = false;
        }
    }//GEN-LAST:event_pilihanActionPerformed

    private void nextDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextDayActionPerformed
        // Ganti Hari
        if (jenisPohon == 0) {
            JOptionPane.showMessageDialog(null, "Silahkan melakukan pembersihan lahan!");
        } else {
            hari += 1;
            day.setText(String.valueOf(hari));
            statusAir -= 20;
            air.setText(String.valueOf(statusAir));
            umurPohon += 1;
            umur.setText(String.valueOf(umurPohon));
            if (statusAir <= 20) {
                JOptionPane.showMessageDialog(null, "Pohon kekeringan, silahkan melakukan penyiraman!");
            }
            if (umurPohon >= maxUmur) {
                JOptionPane.showMessageDialog(null, "Umur pohon sudah mencukupi untuk dilakukan penebangan!");
            }
        }
    }//GEN-LAST:event_nextDayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel air;
    private javax.swing.JLabel day;
    private javax.swing.JLabel f01;
    private javax.swing.JLabel f02;
    private javax.swing.JLabel f03;
    private javax.swing.JLabel f04;
    private javax.swing.JLabel f05;
    private javax.swing.JLabel f06;
    private javax.swing.JLabel f07;
    private javax.swing.JLabel f08;
    private javax.swing.JLabel f09;
    private javax.swing.JLabel f10;
    private javax.swing.JLabel f11;
    private javax.swing.JLabel f12;
    private javax.swing.JLabel f13;
    private javax.swing.JLabel f14;
    private javax.swing.JLabel f15;
    private javax.swing.JLabel f16;
    private javax.swing.JLabel field;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jenis;
    private javax.swing.JButton nextDay;
    private javax.swing.JButton pilihan;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s10;
    private javax.swing.JLabel s11;
    private javax.swing.JLabel s12;
    private javax.swing.JLabel s13;
    private javax.swing.JLabel s14;
    private javax.swing.JLabel s15;
    private javax.swing.JLabel s16;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JLabel s7;
    private javax.swing.JLabel s8;
    private javax.swing.JLabel s9;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t15;
    private javax.swing.JLabel t16;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    private javax.swing.JLabel tanamanke;
    private javax.swing.JLabel umur;
    // End of variables declaration//GEN-END:variables
}
